Solution E-Ticaret/E-Ticaret/Controllers/LoginController.cs
using E_Ticaret.Models.DbContext;
using E_Ticaret.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace E_Ticaret.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
       
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(LogIn userLogIn)
        {
            LogIn user = null;

            User userProfil = null;
                                       
            try
            {
                using (ETicaretDb db = new ETicaretDb())
                {
                    user = db.LogIn.Where(m => m.UserName == userLogIn.UserName.Trim()).FirstOrDefault();

                    if (user != null)
                    {
                        throw new Exception(userLogIn.UserName + " adlı kullanıcı zaten kayıtlı"); 
                    }
                                    
                    db.LogIn.Add(userLogIn);
                    
                    db.SaveChanges();

                    userProfil = new User();

                    userProfil.LogInId = userLogIn.Id;

                    db.User.Add(userProfil);

                    db.SaveChanges();

                    ViewBag.ResultSuccessMessage = "Kayıt başarılı. Giriş Yapabilirsiniz";

                    return View();
                }
            }
            catch (Exception ex)
            {
                ViewBag.ResultMessage = ex.Message ;

                return View(userLogIn);
            }           
        }

        public ActionResult SingIn()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SingIn(LogIn userLogIn)
        {
            LogIn entity = null;

            try
            {
                using (ETicaretDb db = new ETicaretDb())
                {
                    entity = db.LogIn.Where(m => m.UserName == userLogIn.UserName && m.Password == userLogIn.Password).FirstOrDefault();
                }

                if (entity == null)
                {
                    throw new Exception("Kullanıcı Adı veya Parola hatalı");
                }
                else if (entity.UserName == "admin" && entity.Password == "admin")
                {
                    Session["LogInId"] = entity.Id;
                    Session["UserName"] = entity.UserName;
                    return RedirectToAction("Index", "Home", new { area = "Admin" });
                }
                else
                {
                    Session["LogInId"] = entity.Id;
                    Session["UserName"] = entity.UserName;
                }

                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex )
            {
                ViewBag.ResultMessage = ex.Message;

                return View();
            }            
        }

        public ActionResult SignOut()
        {
            Session.RemoveAll();

            return RedirectToAction("Index", "Home");
        }
    }
}

Solution E-Ticaret/E-Ticaret/Controllers/ProductController.cs
using E_Ticaret.ActionFilter;
using E_Ticaret.Models.DbContext;
using E_Ticaret.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace E_Ticaret.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product       
        public ActionResult Index(int categoryId)
        {           
            List<Product> productList = null;

            try
            {
                using (ETicaretDb db = new ETicaretDb())
                {
                    productList = db.Product.Where(m => m.CategoryId == categoryId).ToList();
                }

                return View(productList);
            }
            catch (Exception)
            {
                return Content("Ürünler listelenemedi");
            }
        }

        public ActionResult ProductDetail(int productId)
        {
            Product product = new Product();

            try
            {
                using (ETicaretDb db = new ETicaretDb())
                {
                    product = db.Product.Where(m => m.Id == productId).FirstOrDefault();
                }

                return View(product);
            }
            catch (Exception)
            {
                return Content("Ürün yüklenemedi");
            }          
        }       
    }
}

Solution E-Ticaret/E-Ticaret/Controllers/ProfilController.cs
using E_Ticaret.ActionFilter;
using E_Ticaret.Models;
using E_Ticaret.Models.DbContext;
using E_Ticaret.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace E_Ticaret.Controllers
{
    [AuthenticationControl]
    public class ProfilController : Controller
    {
        // GET: Profil
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            User user = null;

            try
            {
                using (ETicaretDb db = new ETicaretDb())
                {
                    user = db.User.Find(Session["LogInId"]);
                }
            }
            catch (Exception)
            {
                throw;
            }

            return View(user);
        }

        [HttpPost]
        public ActionResult Create(User user)
        {
            user.LogInId = (int)Session["LogInId"];

            try
            {
                using (ETicaretDb db = new ETicaretDb())
                {
                    if (user.LogInId > 0)
                    {
                        db.Entry(user).State = System.Data.Entity.EntityState.Modified;
                    }
                    else
                    {
                        db.User.Add(user);
                    }

                    db.SaveChanges();                   

                    ViewBag.ResultSuccessMessage = "Kayıt başarılı";                   
                }
            }
            catch (Exception)
            {
                ViewBag.ResultMessage = "Kayıt işleminde hata oluştu";              
            }

            return View();
        }
       
        public ActionResult Address(int id = 0)
        {
            int userId = (int)Session["LogInId"];

            AddressMV addressMV = new AddressMV();

            List<Address> addressList = null;

            Address address = new Address();

            try
            {
                using (ETicaretDb db = new ETicaretDb())
                {
                    addressList = db.Address.Where(m => m.UserId == userId).ToList();

                    addressMV.Addresses = addressList;

                    if (id > 0)
                    {
                        address = db.Address.Find(id);
                    }

                    addressMV.Address = address;
                }                            
            }
            catch (Exception)
            {
                throw;
            }

            return View(addressMV);
        }

        [HttpPost]
        public ActionResult Address(Address address)
        {
            AddressMV addressMV = new AddressMV();

            List<Address> addressList = null;

            int userId = (int)Session["LogInId"];

            address.UserId = userId;

            try
            {
                using (ETicaretDb db = new ETicaretDb())
                {
                    if (address.Id > 0)
                    {
                        db.Entry(address).State = System.Data.Entity.EntityState.Modified;
                    }
                    else
                    {
                        db.Address.Add(address);
                    }

                    db.SaveChanges();

                    ModelState.Clear();

                    addressList = db.Address.Where(m => m.UserId == address.UserId).ToList();

                    addressMV.Addresses = addressList;                   
                }                              
            }
            catch (Exception)
            {
                throw;
            }
                       
            return View(addressMV);
        }
    }
}

Solution E-Ticaret/E-Ticaret/Views/Shared/_Layout.cshtml
@using E_Ticaret.Models.Entities

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    
    @if (Session["LogInId"] == null)
    {
        @Html.Partial("_PartialNonUser")            
    }
    else
    {
        @Html.Partial("_PartialUser")
    }
         
    <div class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ana Sayfa", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @foreach (var item in (List<Category>)TempData.Peek("CategoryList"))
                {
                    @Html.ActionLink(item.Name, "Index", "Product", new { area = "", categoryId = item.Id }, new { @class = "navbar-brand" })
                    //TempData.Keep("CategoryList");
                }
                @*@Html.ActionLink("Berjerler", "Index", "Product", new { area = "", categoryId = 1 }, new { @class = "navbar-brand" })
                @Html.ActionLink("Koltuk Takımları", "Index", "Product", new { area = "", categoryId = 2 }, new { @class = "navbar-brand" })
                @Html.ActionLink("Abajurlar", "Index", "Product", new { area = "", categoryId = 3 }, new { @class = "navbar-brand" })
                @Html.ActionLink("Dekoratif Işıklar", "Index", "Product", new { area = "", categoryId = 4 }, new { @class = "navbar-brand" })
                @Html.ActionLink("Ofis Sandalyeleri", "Index", "Product", new { area = "", categoryId = 5 }, new { @class = "navbar-brand" })
                @Html.ActionLink("Avizeler", "Index", "Product", new { area = "", categoryId = 3 }, new { @class = "navbar-brand" })*@                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>          
    <div class="container body-content">               
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Interior Mobilya</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script>
        window.setTimeout(function () {
            $(".alert").fadeTo(1500, 0).slideUp(500, function () {
                $(this).remove();
            });
        }, 3000);
    </script>   
    @RenderSection("scripts", false)
</body>
</html>

Solution E-Ticaret/E-Ticaret/Views/Shared/_PartialAddress.cshtml
<div class="form-group">
    <a id="submit_button" class="btn btn-success" href="@Url.Action("Address", "Profil")" >Adres İşlemleri</a>
</div>

Solution E-Ticaret/E-Ticaret/Views/Shared/_PartialNonUser.cshtml
<div class="navbar">
    <div class="container pull-right">
        @Html.ActionLink("Giriş Yap", "SingIn", "Login", new { area = "" }, new { @class = "navbar-brand" })
        @Html.ActionLink("Kayıt Ol", "Create", "Login", new { area = "" }, new { @class = "navbar-brand" })
    </div>
</div>    

Solution E-Ticaret/E-Ticaret/Views/Shared/_PartialUser.cshtml
<div class="navbar">
    <div class="container pull-right">
        @Html.ActionLink("Çıkış", "SignOut", "Login", new { area = "" }, new { @class = "navbar-brand" })
        @Html.ActionLink("Siparişlerim", "PastBaskets", "Basket", new { area = "", userId = (int)Session["LogInId"] }, new { @class = "navbar-brand" })       
        @Html.ActionLink("Profil", "Create", "Profil", new { area = "" }, new { @class = "navbar-brand" })             
        <a href="@Url.Action("Index","Basket")">
           <img src="~/Images/Basket.png" width="25" height="25" style="margin-right:1px;margin-top:10px">(<span id="cartQuantitySummary">@Session["basketCount"]</span>)
        </a>       
        </div>
    <div class="pull-left">
        <label style="margin-left:15px; margin-top:15px">Hoş Geldiniz @Session["UserName"]</label>       
    </div>
</div>